
#devtools::install_github("cloudyr/aws.ec2")
library(aws.ec2)
library(ssh)
library(remoter)
library(tidyverse)
#usethis::edit_r_environ()


# helper functions -------------------------------------------------------------

#' This function generates a random password
#' that can be used as a temporary password during the current session.
#' It helps with avoiding hard-coded passwords.
generate_password <- function(n = 20) {
  # letters
  letters %>% 
    # and numbers
    c(0:9) %>% 
    # randomly combined
    sample(size = n, replace = TRUE) %>% 
    str_c(collapse = '')
}


#' This function spins up a fresh AWS EC2 instance
#' and adds the current local ip to a new permissions group
launch_ec2_instance <- function(
  aws_ami,
  aws_type = "t2.micro"
) {
  # use existing ip address or create a new one
  ips <- describe_ips()
  if (!length(ips)) {
    ips[[1L]] <- allocate_ip("vpc")
  }
  s <- describe_subnets()
  g <- describe_sgroups()
  
  # Check your VPC and Security Group settings
  aws_subnets <- describe_subnets()
  aws_sgroup <- create_sgroup(
    name = paste0("tmp_ec2_sg_localip_", ips[[1L]]["publicIp"]), 
    description = paste0("Allow my current IP: ", ips[[1L]]["publicIp"]),
    vpc = aws_subnets[[1L]])
  
  # Launch the instance using appropriate settings
  aws_instance <- run_instances(
    image = aws_ami, 
    type = aws_type,
    subnet = s[[1]], 
    sgroup = g[[1]])
  Sys.sleep(20L) # wait for instance to boot
  
  # associate IP address with instance
  instance_ip <- get_instance_public_ip(aws_instance)
  if (is.na(instance_ip)) {
    instance_ip <- associate_ip(aws_instance, ips[[1L]])$publicIp
  }
  # authorize access from this IP
  try(authorize_ingress(aws_sgroup))
  try(authorize_egress(aws_sgroup))
  
  # write and return output list
  ec2info <- list(
    "security_group" = aws_sgroup,
    "ips" = ips[[1L]],
    "instance" = aws_instance
  )
  return(ec2info)
}


#' This function takes a freshly spun up instance object from
#' aws.ec2 and waits until it sees the status switched to running.
wait_for_ec2_instance <- function(aws_instance) {
  state <- "unknown"
  # wait until booted
  while(state != "running") {
    message('waiting...')
    Sys.sleep(5)
    # get instance state from description
    instance <- aws.ec2::describe_instances(aws_instance)
    state <- instance[[1]][["instancesSet"]][[1]][["instanceState"]][["name"]]
  }
  message("instance running!")
  return(instance)
}


#' This function expects an input as generated by `launch_ec2_instance`.
#' It shuts down and terminates the given instances and revokes the temporary
#' security groups that were created.
terminate_and_cleanup <- function(ec2info) {
  
  # stop and terminate the instance
  stop_instances(ec2info[["instance"]])
  terminate_instances(ec2info[["instance"]])
  
  # revoke access from this IP to security group
  try(revoke_ingress(ec2info[["security_group"]]))
  try(revoke_egress(ec2info[["security_group"]]))
  
  # release IP address
  release_ip(ec2info[["ips"]])
}


# spin up instance -------------------------------------------------------------

# get local aws credentials
aws_credentials <- aws.signature::locate_credentials()
Sys.setenv(
  "AWS_ACCESS_KEY_ID" = aws_credentials$key,
  "AWS_SECRET_ACCESS_KEY" = aws_credentials$secret,
  "AWS_DEFAULT_REGION" = "eu-west-2"
)
# set parameters
aws_ami <- "ami-06485bfe40a86470d"
aws_describe <- describe_images(aws_ami)
aws_type <- "t2.micro"

# launch machine and retain both instance and securitygroup info
ec2info <- launch_ec2_instance(aws_ami, aws_type = "t2.micro")
ec2instance <- ec2info[["instance"]]

# wait for machine to start
ec2instance <- wait_for_ec2_instance(ec2instance)
# get ip address
ec2ip <- get_instance_public_ip(ec2instance)


# connect via ssh --------------------------------------------------------------

# ssh connection
username <- system("whoami", intern = TRUE)
con <- ssh_connect(host = paste(username, ec2ip, sep = "@"))

# start remoter::server on instance
random_tmp_password <- generate_password()
r_cmd_start_remoter <- str_c(
  "sudo Rscript -e ",
  "'remoter::server(",
  "port = 55555, ",
  "password = %pwd, ",
  "showmsg = TRUE)'",
  collapse = "") %>%
  str_replace("%pwd", str_c('"', random_tmp_password, '"'))

# connect and execute
plan(multicore)
x <- future(
  ssh_exec_wait(
    session = con, 
    command = r_cmd_start_remoter))

ssh_disconnect(con)


# connect via remoter ----------------------------------------------------------

remoter::client(
  addr = ec2ip, 
  port = 55555,
  password = random_tmp_password,
  prompt = "remoter")

### YOUR CODE COES HERE...



# clean up ---------------------------------------------------------------------

# Only if still on remoter:
shutdown()

# save all your work before doing this!
terminate_and_cleanup(ec2info)

